sudo: false
language: perl
perl:
  - "5.16"
  - "5.22"
env:
  global:
    - secure: "NroWmwo87rKc5VoqNCzySJjNiEeBl/Ryv9d/IZ4swEzxbLVmzGPJgqbw7TmhHLS7X+r3WcAVHnO3ERaxPVFSUu/yclls4IGnwoocYV/tLjF5vMCqdF0MtLF/GTPtNyv9JyzKx9fkBNlwxYgtv9c25JKfv4I1MvXdMEVRe9f4e8U="
    - TEST_AUTHOR=1
    - DNAP_UTILITIES_VERSION="0.5.1"
before_install:
  - cpanm --no-lwp --notest https://github.com/wtsi-npg/perl-dnap-utilities/releases/download/${DNAP_UTILITIES_VERSION}/WTSI-DNAP-Utilities-${DNAP_UTILITIES_VERSION}.tar.gz
  - cpanm --installdeps --notest .
after_success:
  - ./Build dist
  - export DIST_FILE=$(ls ml_warehouse-*.tar.gz)
  - export MD5_FILE=$DIST_FILE.md5
  - md5sum $DIST_FILE > $MD5_FILE
  - export SHA256_FILE=$DIST_FILE.sha256
  - shasum -a 256 $DIST_FILE > $SHA256_FILE
deploy:
  provider: releases
  api-key: $GH_OAUTH
  file:
    - $DIST_FILE
    - $MD5_FILE
    - $SHA256_FILE
  skip_cleanup: true
  on:
    perl: 5.16
    tags: true
    all_branches: true

